# The Teamscale IDE configuration file format version of this file.
version = "1.0" # Optional, default: 1.0

root = true

[server]
# The URL of the Teamscale instance.
url = "https://p7s1.teamscale.io/" 

[project]

# The Project ID of the Teamscale project.
id = "testla-screenplay-core-py"

# The branch to use for retrieving data from the server.
branch = "main"